// flow-typed signature: f06b48361d1baad37df8d97fb9c6cc2f
// flow-typed version: <<STUB>>/tachyons_v^4.7.4/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
